apiVersion: v1
kind: Service
metadata:
  name: kareer-user
  namespace: backend
spec:
  selector:
    app: kareer-user
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
